//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bump.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MLResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MLResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bump.Languages.MLResource", typeof(MLResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        internal static string Back_Home {
            get {
                return ResourceManager.GetString("Back_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUMP.
        /// </summary>
        internal static string BUMP {
            get {
                return ResourceManager.GetString("BUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be Careful, there&apos;s a bump in front of you half a kilometer away.
        /// </summary>
        internal static string BumpAlert {
            get {
                return ResourceManager.GetString("BumpAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can contact us:.
        /// </summary>
        internal static string contact_describe {
            get {
                return ResourceManager.GetString("contact_describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute.
        /// </summary>
        internal static string Contribute {
            get {
                return ResourceManager.GetString("Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email /Username.
        /// </summary>
        internal static string Email_Username {
            get {
                return ResourceManager.GetString("Email_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please later.
        /// </summary>
        internal static string FailedSetDanger {
            get {
                return ResourceManager.GetString("FailedSetDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can follow us:.
        /// </summary>
        internal static string follow {
            get {
                return ResourceManager.GetString("follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password ?.
        /// </summary>
        internal static string Forget_Password {
            get {
                return ResourceManager.GetString("Forget_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have account?.
        /// </summary>
        internal static string Have_account {
            get {
                return ResourceManager.GetString("Have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heba AL-ahmad.
        /// </summary>
        internal static string Heba {
            get {
                return ResourceManager.GetString("Heba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Use.
        /// </summary>
        internal static string How_Use {
            get {
                return ResourceManager.GetString("How_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite a friend.
        /// </summary>
        internal static string Invite_friend {
            get {
                return ResourceManager.GetString("Invite_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us.
        /// </summary>
        internal static string Join_us {
            get {
                return ResourceManager.GetString("Join_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joud AL-dhadleh .
        /// </summary>
        internal static string Joud {
            get {
                return ResourceManager.GetString("Joud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to be a builder of our unique team, please do sign up..
        /// </summary>
        internal static string login_describe {
            get {
                return ResourceManager.GetString("login_describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string Mobile_Number {
            get {
                return ResourceManager.GetString("Mobile_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?  .
        /// </summary>
        internal static string new_account {
            get {
                return ResourceManager.GetString("new_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the bump is 50m from where you are standing.
        /// </summary>
        internal static string notification {
            get {
                return ResourceManager.GetString("notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Program.
        /// </summary>
        internal static string Our_Program {
            get {
                return ResourceManager.GetString("Our_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        internal static string Our_Team {
            get {
                return ResourceManager.GetString("Our_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email associated with your account and we&apos;ll send an email with instruction to reset your password..
        /// </summary>
        internal static string password_describe {
            get {
                return ResourceManager.GetString("password_describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful, there is construction in front of you half a kilometer.
        /// </summary>
        internal static string PitAlert {
            get {
                return ResourceManager.GetString("PitAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goal is  preserving your safety and the safety of the car on the highway..
        /// </summary>
        internal static string prog_A {
            get {
                return ResourceManager.GetString("prog_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through the application, you can determine what matters most to you as a driver on the road, such as a nearby bump, speed radar, or new pits, locating the nearest gas station to avoid running out of fuel at any time..
        /// </summary>
        internal static string prog_B {
            get {
                return ResourceManager.GetString("prog_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alone we can do so little; together we can do so much..
        /// </summary>
        internal static string quote {
            get {
                return ResourceManager.GetString("quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raghad AL-khateeb.
        /// </summary>
        internal static string Raghad {
            get {
                return ResourceManager.GetString("Raghad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saja AL-dahadha.
        /// </summary>
        internal static string Saja {
            get {
                return ResourceManager.GetString("Saja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string Send_Email {
            get {
                return ResourceManager.GetString("Send_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Suggestions.
        /// </summary>
        internal static string Send_Suggestions {
            get {
                return ResourceManager.GetString("Send_Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing  in.
        /// </summary>
        internal static string Sing_in {
            get {
                return ResourceManager.GetString("Sing_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Sing in.
        /// </summary>
        internal static string Social_Singin {
            get {
                return ResourceManager.GetString("Social_Singin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce your speed now, you have a radar half a kilometer away.
        /// </summary>
        internal static string SpeedAlert {
            get {
                return ResourceManager.GetString("SpeedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The danger site has been saved successfully, thank you.
        /// </summary>
        internal static string SuccessedSetDanger {
            get {
                return ResourceManager.GetString("SuccessedSetDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        internal static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can send any suggestions or feedback to help us begin better.
        /// </summary>
        internal static string suggestions_describe {
            get {
                return ResourceManager.GetString("suggestions_describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application gives a distance notice that allows you to take an appropriate measure to protect yourself and your car as well, to do this you should allow the application to access your location and select what you like to detection in your way..
        /// </summary>
        internal static string use_A {
            get {
                return ResourceManager.GetString("use_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can help us and be contribute to search and enter the location of every thing in the way, you should sign up to do this..
        /// </summary>
        internal static string use_B {
            get {
                return ResourceManager.GetString("use_B", resourceCulture);
            }
        }
    }
}
